---
# task to handle cx_oracle dependency

- name: mkdir /opt/ora
  file: path=/opt/ora state=directory

- name: download instantclient_12_1
  get_url: 
    url: "{{python_scl_instantclient_url}}"
    dest: /tmp/{{python_scl_instantclient_folder}}
    mode: 0440

- name: unarchive instantclient_12_1
  unarchive: 
    src: /tmp/{{python_scl_instantclient_folder}}
    dest: /opt/ora
    remote_src: True

- name: create cx_oracle.conf
  file: 
    path: /etc/ld.so.conf.d/cx_oracle.conf 
    state: touch 
    owner: root
    group: root 
    mode: 0440

- name: edit cx_oracle.conf
  blockinfile: 
    dest: /etc/ld.so.conf.d/cx_oracle.conf
    block: |
      /opt/ora/instantclient_12_1

- name: update ldconfig
  shell: ldconfig